### PR TITLE
Add enable/DisableAll keys link

### PR DESCRIPTION
**Pull request by julien-vidal**
On large store, it can be handy to have a link to enable or disable all entries.

### CODE REVIEW

**Review by yannickglt — APPROVED** [review]

**Comment by yannickglt** [comment]
I would have seen a single toggle like: 
- Text displaying `Enable all` and `enabled` to `false` if there's at least one disabled.
- Text displaying `Disable all` and `enabled` to `true` if all are enabled.
WDYT?

**Comment by julien-vidal** [comment]
I pick this option, because in case of large store, you can have some keys to true and some to false.

In that case, sometimes you wanna choose to enable all or disable all...

With a toggle, you are forced to click twice depending of your use case.

If you prefer a toggle, I'll do it else I let this PR like that ^^.

**Comment by julien-vidal** [comment]
@yannickglt I made what you suggested.
Only one thing annoy me in code I create 

https://github.com/yannickglt/store-devtools-switcher/pull/3/files#diff-a20ef8f6339e0789f5bede667f465603R38

I can't do that with ts 😢 
```
// const {[SwitchActionKeys.DisableAll]: disableAction, [SwitchActionKeys.EnableAll]: enable, ...filteredObject} = extendedState
```

If you have an idea ...

**Comment by julien-vidal** [comment]
Seems I had to add `tslib` in order to make it work 😉 
Ready to review !

**Review by yannickglt — APPROVED** [review]

**Pull request merged**
